name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install pnpm
        run: npm install pnpm -g
      - name: pnpm install
        run: pnpm install --ignore-scripts
      - name: run tests
        run: pnpm run test:all
        env:
          CI: 'true'
      - name: run build
        run: pnpm run build:all
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/master'
