name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install pnpm
        run: npm install pnpm -g

      - name: pnpm install
        run: pnpm install --ignore-scripts

      - name: run build
        run: pnpm run build:all

      - name: run tests
        run: pnpm run test:all
        env:
          CI: 'true'

      - name: Create Release and Publish
        uses: changesets/action@master
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
